### ISSUE TITLE
RCall Build error on windows 7 64

### ISSUE THREAD

**Issue by datnamer** [JuliaStats/RCall.jl#22]
Hello,

I'm getting  "Unable to load the LibR.dll" when trying to add and build RCall.

I have set the R exe and RScript in my windows path.

Any help would be appreciated. 

Thanks

Julia version 3.5 64 bit for windows

**Comment by datnamer** [comment]
Now I have a new error message: "could not spawn `Rscript -e 'for (nm in c("R_HOME","R_DOC_DIR","R_INCLUDE_DIR","R_SHARE_DIR","LD_LIBRARY_PATH")) print(Sys.getenv(nm),quote=FALSE)'`: no such file or directory (ENOENT)
while loading C:\Users\User\.julia\v0.3\RCall\deps\build.jl, in expression starting on line 3"

My RCall/deps directory only has gitignore and build.jl, but Pkg.dir("RCall","deps","deps.jl") points me to deps.jl. Any suggestions please?

**Comment by dmbates** [comment]
Earlier you said the you have set Rscript (capitalization may be important) on your windows path but the error message says that it could not spawn an Rscript process.  You can check by starting Julia and entering
```julia
; Rscript<Enter>
```
The prompt should change after you type the `;`  and the result should be something like

```
shell> Rscript
Usage: /path/to/Rscript [--options] [-e expr [-e expr2 ...] | file] [args]

--options accepted are
  --help              Print usage and exit
  --version           Print version and exit
  --verbose           Print information on progress
  --default-packages=list
                      Where 'list' is a comma-separated set
                        of package names, or 'NULL'
or options to R, in addition to --slave --no-restore, such as
  --save              Do save workspace at the end of the session
  --no-environ        Don't read the site and user environment files
  --no-site-file      Don't read the site-wide Rprofile
  --no-init-file      Don't read the user R profile
  --restore           Do restore previously saved objects at startup
  --vanilla           Combine --no-save, --no-restore, --no-site-file
                        --no-init-file and --no-environ

'file' may contain spaces but not shell metacharacters
Expressions (one or more '-e <expr>') may be used *instead* of 'file'
See also  ?Rscript  from within R
```

If this doesn't happen then you need to determine what the shell from within Julia sees as a path.  Unfortunately that is well beyond my understanding of Windows.

Because you asked, the script `deps/build.jl` is what creates the file `deps/deps.jl` by running `Rscript`.

There is a workaround which is to start R or RStudio and execute the line
```R
for (nm in c("R_HOME","R_DOC_DIR","R_INCLUDE_DIR","R_SHARE_DIR","LD_LIBRARY_PATH")) print(Sys.getenv(nm),quote=FALSE)
```

to obtain suitable values for those environment variables.  That's all that the `deps/build.jl` script is doing.

**Comment by simonbyrne** [comment]
@datnamer Hopefully this should be working on Windows now. Would you be willing to give it a try?

**Comment by simonbyrne** [comment]
Please reopen if this is still an issue.
