### ISSUE TITLE
R custom string literal

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/RCall.jl#48]
It might be nice to be able to call R code via a macro string literal, similar to this proposal: https://github.com/JuliaLang/MATLAB.jl/pull/29.

Of course, one problem would be that using `$` for variable substitution would conflict with R lookup usage.

**Comment by randy3k** [comment]
I believe there is no problem of using `$`. With this macro,
```julia
macro s_mstr(x)
    quote
        rprint($x)
    end
end
```
there is no problem in extracting the list element by using `$`:
```julia
julia> s"""
       x = list(a=1,b=2)
       y = x$a
       """
[1] 1
```

**Comment by simonbyrne** [comment]
Sorry, what I meant was that it might be difficult to use `$` the same way the proposed `mat_str` macro does, i.e. for copying the corresponding julia variable to R.

**Comment by simonster** [comment]
You could allow only `$` followed by parens, e.g. `$(a)`, unless that's actually valid R syntax in some context. I believe you could backslash-escape other cases of `$` before passing to the parser.

The hardest part in JuliaLang/MATLAB.jl#29 was determining whether a variable/expression is assigned or used. This is easier for MATLAB than other languages because the MATLAB parser sucks and can't itself handle cases that would be hard for us to handle, but it still turned out to be non-trivial. However, if you can actually get the AST from R, this might not be too hard.

**Comment by randy3k** [comment]
This can also be closed by https://github.com/JuliaStats/RCall.jl/pull/94.
