### ISSUE TITLE
ErrorException after install

### ISSUE THREAD

**Issue by robertfeldt** [JuliaStats/RCall.jl#8]
Thanks for RCall it looks very useful. I followed the installation steps in the README on a fresh Julia 0.3.4 on Mac OS X Yosemite with all packages updated but then get this when trying to load RCall:

    julia> using RCall
    Warning: error initializing module RCall:
    ErrorException("type cannot be constructed")

The deps.jl file looks fine except for the LD_LIBRARY_PATH:

    feldt:~/feldt/bin$ cat /Users/feldt/.julia/v0.3/RCall/deps/deps.jl
    # This is an auto-generated file; do not edit

    const libR="/usr/local/Cellar/r/3.1.1/R.framework/Resources/lib/libR.dylib"
    ENV["R_HOME"]="/usr/local/Cellar/r/3.1.1/R.framework/Resources"
    ENV["R_DOC_DIR"]="/usr/local/Cellar/r/3.1.1/R.framework/Resources/doc"
    ENV["R_INCLUDE_DIR"]="/usr/local/Cellar/r/3.1.1/R.framework/Resources/include"
    ENV["R_SHARE_DIR"]="/usr/local/Cellar/r/3.1.1/R.framework/Resources/share"
    ENV["LD_LIBRARY_PATH"]=""

so I changed it to

    ENV["LD_LIBRARY_PATH"]="/usr/local/Cellar/r/3.1.1/R.framework/Resources/lib"

but with same error. Any ideas on what is wrong here? Thanks in advance.

**Comment by randy3k** [comment]
I confirm that it is a problem of v0.3.
But it works for v0.4.

**Comment by robertfeldt** [comment]
Thanks Randy. Will try 0.4 also on my side to confirm this.

**Comment by robertfeldt** [comment]
Ok I tried on fresh nightly ( Version 0.4.0-dev+2558 (2015-01-08 07:21 UTC) ) install and RCall works also for me as for randy. So my problem is only on 0.3.4.

**Comment by dmbates** [comment]
The same error occurs under julia-0.3.4 on Ubuntu, 64-bit and it does appear to be a version 0.3.x versus version 0.4 issue.  In retrospect it would have been better for me to start development under version 0.3.x and then forward-port to version 0.4 instead of the other way around.

The __init__ function is defined in RCall/src/Rcall.jl.  Its purpose is to establish certain package-wide identifiers when the package is attached.  Adding some `@show` macro calls in that function to see when the error originates would help.

**Comment by randy3k** [comment]
In v0.4, all converters are constructor, but not in v0.3.
[see here](https://github.com/JuliaLang/julia/blob/2fdaf10d3abf5189d60dc70cd9829e4b9ecfaf76/base/base.jl#L35)

So `Int(1.0)` is fine on v0.4, but not in v0.3.
Patch has been submitted.

**Comment by dmbates** [comment]
https://github.com/randy3k/RCall.jl/commit/a45bb1a643d6493fefc9bc9cc488d70268970c88
